### PR TITLE
[FEATURE] Implement validator domain verification

### PR DESCRIPTION
**Pull request by wilsonianb**
DEC-190

### CODE REVIEW

**Comment by stevenzeiler** [comment]
Have you tried including this module in another module using the package.json? I'm not sure npm supports loading of babel/es6 features.

**Comment by wilsonianb** [comment]
I'll try that now

**Comment by stevenzeiler** [comment]
Either way I would say it is okay to merge since the tests pass, and if babel isn't supported by npm then the current master won't work either.

**Comment by stevenzeiler** [comment]
:+1: LGTM

**Pull request merged**
